/*
* Game-Deception Blank Wrapper v2
* Copyright (c) Crusader 2002
*/

#ifndef H_OPENGL32
#define H_OPENGL32

#define ORIGINAL_DLL	"opengl32.dll"

/* Original function typedefs */
#include <windows.h>
#include <stdio.h>
#include <stdarg.h>
#include <time.h>
#include <gl/gl.h>
#include <gl/glu.h>
//#include <gl/glaux.h>
#include <math.h>

#define WANT_OPENGL
#include "cgamex86.h"

#ifdef __cplusplus
extern "C" {
#endif

#define GL_NORMAL_MAP_ARB                   0x8511
#define GL_REFLECTION_MAP_ARB               0x8512
#define GL_TEXTURE_CUBE_MAP_ARB             0x8513
#define GL_TEXTURE_BINDING_CUBE_MAP_ARB     0x8514
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB  0x8515
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB  0x8516
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB  0x8517
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB  0x8518
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB  0x8519
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB  0x851A
#define GL_PROXY_TEXTURE_CUBE_MAP_ARB       0x851B
#define GL_MAX_CUBE_MAP_TEXTURE_SIZE_ARB    0x851C
//#define GL_TEXTURE_WRAP_R                   0x2804
#define GL_CLAMP_TO_EDGE                    0x812F

extern BOOL glInit (void);
//extern void __cdecl add_log ( const char * fmt, ... );
extern HMODULE hOpenGL;

typedef void ( WINAPI *func_glActiveTextureARB_t) (GLenum target);
typedef void ( WINAPI *func_BindTextureEXT_t) (GLenum target, GLuint texture);
typedef void ( WINAPI *func_glMultiTexCoord2fARB_t) (GLenum target, GLfloat s, GLfloat t);
typedef void ( WINAPI *func_glAccum_t) (GLenum op,  GLfloat value);
typedef void ( WINAPI *func_glAlphaFunc_t) (GLenum func,  GLclampf ref);
typedef GLboolean ( WINAPI *func_glAreTexturesResident_t) (GLsizei n,  const GLuint *textures,  GLboolean *residences);
typedef void ( WINAPI *func_glArrayElement_t) (GLint i);
typedef void ( WINAPI *func_glBegin_t) (GLenum mode);
typedef void ( WINAPI *func_glBindTexture_t) (GLenum target,  GLuint texture);
typedef void ( WINAPI *func_glBitmap_t) (GLsizei width,  GLsizei height,  GLfloat xorig,  GLfloat yorig,  GLfloat xmove,  GLfloat ymove,  const GLubyte *bitmap);
typedef void ( WINAPI *func_glBlendFunc_t) (GLenum sfactor,  GLenum dfactor);
typedef void ( WINAPI *func_glCallList_t) (GLuint list);
typedef void ( WINAPI *func_glCallLists_t) (GLsizei n,  GLenum type,  const GLvoid *lists);
typedef void ( WINAPI *func_glClear_t) (GLbitfield mask);
typedef void ( WINAPI *func_glClearAccum_t) (GLfloat red,  GLfloat green,  GLfloat blue,  GLfloat alpha);
typedef void ( WINAPI *func_glClearColor_t) (GLclampf red,  GLclampf green,  GLclampf blue,  GLclampf alpha);
typedef void ( WINAPI *func_glClearDepth_t) (GLclampd depth);
typedef void ( WINAPI *func_glClearIndex_t) (GLfloat c);
typedef void ( WINAPI *func_glClearStencil_t) (GLint s);
typedef void ( WINAPI *func_glClipPlane_t) (GLenum plane,  const GLdouble *equation);
typedef void ( WINAPI *func_glColor3b_t) (GLbyte red,  GLbyte green,  GLbyte blue);
typedef void ( WINAPI *func_glColor3bv_t) (const GLbyte *v);
typedef void ( WINAPI *func_glColor3d_t) (GLdouble red,  GLdouble green,  GLdouble blue);
typedef void ( WINAPI *func_glColor3dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glColor3f_t) (GLfloat red,  GLfloat green,  GLfloat blue);
typedef void ( WINAPI *func_glColor3fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glColor3i_t) (GLint red,  GLint green,  GLint blue);
typedef void ( WINAPI *func_glColor3iv_t) (const GLint *v);
typedef void ( WINAPI *func_glColor3s_t) (GLshort red,  GLshort green,  GLshort blue);
typedef void ( WINAPI *func_glColor3sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glColor3ub_t) (GLubyte red,  GLubyte green,  GLubyte blue);
typedef void ( WINAPI *func_glColor3ubv_t) (const GLubyte *v);
typedef void ( WINAPI *func_glColor3ui_t) (GLuint red,  GLuint green,  GLuint blue);
typedef void ( WINAPI *func_glColor3uiv_t) (const GLuint *v);
typedef void ( WINAPI *func_glColor3us_t) (GLushort red,  GLushort green,  GLushort blue);
typedef void ( WINAPI *func_glColor3usv_t) (const GLushort *v);
typedef void ( WINAPI *func_glColor4b_t) (GLbyte red,  GLbyte green,  GLbyte blue,  GLbyte alpha);
typedef void ( WINAPI *func_glColor4bv_t) (const GLbyte *v);
typedef void ( WINAPI *func_glColor4d_t) (GLdouble red,  GLdouble green,  GLdouble blue,  GLdouble alpha);
typedef void ( WINAPI *func_glColor4dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glColor4f_t) (GLfloat red,  GLfloat green,  GLfloat blue,  GLfloat alpha);
typedef void ( WINAPI *func_glColor4fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glColor4i_t) (GLint red,  GLint green,  GLint blue,  GLint alpha);
typedef void ( WINAPI *func_glColor4iv_t) (const GLint *v);
typedef void ( WINAPI *func_glColor4s_t) (GLshort red,  GLshort green,  GLshort blue,  GLshort alpha);
typedef void ( WINAPI *func_glColor4sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glColor4ub_t) (GLubyte red,  GLubyte green,  GLubyte blue,  GLubyte alpha);
typedef void ( WINAPI *func_glColor4ubv_t) (const GLubyte *v);
typedef void ( WINAPI *func_glColor4ui_t) (GLuint red,  GLuint green,  GLuint blue,  GLuint alpha);
typedef void ( WINAPI *func_glColor4uiv_t) (const GLuint *v);
typedef void ( WINAPI *func_glColor4us_t) (GLushort red,  GLushort green,  GLushort blue,  GLushort alpha);
typedef void ( WINAPI *func_glColor4usv_t) (const GLushort *v);
typedef void ( WINAPI *func_glColorMask_t) (GLboolean red,  GLboolean green,  GLboolean blue,  GLboolean alpha);
typedef void ( WINAPI *func_glColorMaterial_t) (GLenum face,  GLenum mode);
typedef void ( WINAPI *func_glColorPointer_t) (GLint size,  GLenum type,  GLsizei stride,  const GLvoid *pointer);
typedef void ( WINAPI *func_glCopyPixels_t) (GLint x,  GLint y,  GLsizei width,  GLsizei height,  GLenum type);
typedef void ( WINAPI *func_glCopyTexImage1D_t) (GLenum target,  GLint level,  GLenum internalFormat,  GLint x,  GLint y,  GLsizei width,  GLint border);
typedef void ( WINAPI *func_glCopyTexImage2D_t) (GLenum target,  GLint level,  GLenum internalFormat,  GLint x,  GLint y,  GLsizei width,  GLsizei height,  GLint border);
typedef void ( WINAPI *func_glCopyTexSubImage1D_t) (GLenum target,  GLint level,  GLint xoffset,  GLint x,  GLint y,  GLsizei width);
typedef void ( WINAPI *func_glCopyTexSubImage2D_t) (GLenum target,  GLint level,  GLint xoffset,  GLint yoffset,  GLint x,  GLint y,  GLsizei width,  GLsizei height);
typedef void ( WINAPI *func_glCullFace_t) (GLenum mode);
typedef void ( WINAPI *func_glDebugEntry_t) (void);
typedef void ( WINAPI *func_glDeleteLists_t) (GLuint list,  GLsizei range);
typedef void ( WINAPI *func_glDeleteTextures_t) (GLsizei n,  const GLuint *textures);
typedef void ( WINAPI *func_glDepthFunc_t) (GLenum func);
typedef void ( WINAPI *func_glDepthMask_t) (GLboolean flag);
typedef void ( WINAPI *func_glDepthRange_t) (GLclampd zNear,  GLclampd zFar);
typedef void ( WINAPI *func_glDisable_t) (GLenum cap);
typedef void ( WINAPI *func_glDisableClientState_t) (GLenum array);
typedef void ( WINAPI *func_glDrawArrays_t) (GLenum mode,  GLint first,  GLsizei count);
typedef void ( WINAPI *func_glDrawBuffer_t) (GLenum mode);
typedef void ( WINAPI *func_glDrawElements_t) (GLenum mode,  GLsizei count,  GLenum type,  const GLvoid *indices);
typedef void ( WINAPI *func_glDrawPixels_t) (GLsizei width,  GLsizei height,  GLenum format,  GLenum type,  const GLvoid *pixels);
typedef void ( WINAPI *func_glEdgeFlag_t) (GLboolean flag);
typedef void ( WINAPI *func_glEdgeFlagPointer_t) (GLsizei stride,  const GLvoid *pointer);
typedef void ( WINAPI *func_glEdgeFlagv_t) (const GLboolean *flag);
typedef void ( WINAPI *func_glEnable_t) (GLenum cap);
typedef void ( WINAPI *func_glEnableClientState_t) (GLenum array);
typedef void ( WINAPI *func_glEnd_t) (void);
typedef void ( WINAPI *func_glEndList_t) (void);
typedef void ( WINAPI *func_glEvalCoord1d_t) (GLdouble u);
typedef void ( WINAPI *func_glEvalCoord1dv_t) (const GLdouble *u);
typedef void ( WINAPI *func_glEvalCoord1f_t) (GLfloat u);
typedef void ( WINAPI *func_glEvalCoord1fv_t) (const GLfloat *u);
typedef void ( WINAPI *func_glEvalCoord2d_t) (GLdouble u,  GLdouble v);
typedef void ( WINAPI *func_glEvalCoord2dv_t) (const GLdouble *u);
typedef void ( WINAPI *func_glEvalCoord2f_t) (GLfloat u,  GLfloat v);
typedef void ( WINAPI *func_glEvalCoord2fv_t) (const GLfloat *u);
typedef void ( WINAPI *func_glEvalMesh1_t) (GLenum mode,  GLint i1,  GLint i2);
typedef void ( WINAPI *func_glEvalMesh2_t) (GLenum mode,  GLint i1,  GLint i2,  GLint j1,  GLint j2);
typedef void ( WINAPI *func_glEvalPoint1_t) (GLint i);
typedef void ( WINAPI *func_glEvalPoint2_t) (GLint i,  GLint j);
typedef void ( WINAPI *func_glFeedbackBuffer_t) (GLsizei size,  GLenum type,  GLfloat *buffer);
typedef void ( WINAPI *func_glFinish_t) (void);
typedef void ( WINAPI *func_glFlush_t) (void);
typedef void ( WINAPI *func_glFogf_t) (GLenum pname,  GLfloat param);
typedef void ( WINAPI *func_glFogfv_t) (GLenum pname,  const GLfloat *params);
typedef void ( WINAPI *func_glFogi_t) (GLenum pname,  GLint param);
typedef void ( WINAPI *func_glFogiv_t) (GLenum pname,  const GLint *params);
typedef void ( WINAPI *func_glFrontFace_t) (GLenum mode);
typedef void ( WINAPI *func_glFrustum_t) (GLdouble left,  GLdouble right,  GLdouble bottom,  GLdouble top,  GLdouble zNear,  GLdouble zFar);
typedef GLuint ( WINAPI *func_glGenLists_t) (GLsizei range);
typedef void ( WINAPI *func_glGenTextures_t) (GLsizei n,  GLuint *textures);
typedef void ( WINAPI *func_glGetBooleanv_t) (GLenum pname,  GLboolean *params);
typedef void ( WINAPI *func_glGetClipPlane_t) (GLenum plane,  GLdouble *equation);
typedef void ( WINAPI *func_glGetDoublev_t) (GLenum pname,  GLdouble *params);
typedef GLenum ( WINAPI *func_glGetError_t) (void);
typedef void ( WINAPI *func_glGetFloatv_t) (GLenum pname,  GLfloat *params);
typedef void ( WINAPI *func_glGetIntegerv_t) (GLenum pname,  GLint *params);
typedef void ( WINAPI *func_glGetLightfv_t) (GLenum light,  GLenum pname,  GLfloat *params);
typedef void ( WINAPI *func_glGetLightiv_t) (GLenum light,  GLenum pname,  GLint *params);
typedef void ( WINAPI *func_glGetMapdv_t) (GLenum target,  GLenum query,  GLdouble *v);
typedef void ( WINAPI *func_glGetMapfv_t) (GLenum target,  GLenum query,  GLfloat *v);
typedef void ( WINAPI *func_glGetMapiv_t) (GLenum target,  GLenum query,  GLint *v);
typedef void ( WINAPI *func_glGetMaterialfv_t) (GLenum face,  GLenum pname,  GLfloat *params);
typedef void ( WINAPI *func_glGetMaterialiv_t) (GLenum face,  GLenum pname,  GLint *params);
typedef void ( WINAPI *func_glGetPixelMapfv_t) (GLenum map,  GLfloat *values);
typedef void ( WINAPI *func_glGetPixelMapuiv_t) (GLenum map,  GLuint *values);
typedef void ( WINAPI *func_glGetPixelMapusv_t) (GLenum map,  GLushort *values);
typedef void ( WINAPI *func_glGetPointerv_t) (GLenum pname,  GLvoid* *params);
typedef void ( WINAPI *func_glGetPolygonStipple_t) (GLubyte *mask);
typedef const GLubyte * ( WINAPI *func_glGetString_t) (GLenum name);
typedef void ( WINAPI *func_glGetTexEnvfv_t) (GLenum target,  GLenum pname,  GLfloat *params);
typedef void ( WINAPI *func_glGetTexEnviv_t) (GLenum target,  GLenum pname,  GLint *params);
typedef void ( WINAPI *func_glGetTexGendv_t) (GLenum coord,  GLenum pname,  GLdouble *params);
typedef void ( WINAPI *func_glGetTexGenfv_t) (GLenum coord,  GLenum pname,  GLfloat *params);
typedef void ( WINAPI *func_glGetTexGeniv_t) (GLenum coord,  GLenum pname,  GLint *params);
typedef void ( WINAPI *func_glGetTexImage_t) (GLenum target,  GLint level,  GLenum format,  GLenum type,  GLvoid *pixels);
typedef void ( WINAPI *func_glGetTexLevelParameterfv_t) (GLenum target,  GLint level,  GLenum pname,  GLfloat *params);
typedef void ( WINAPI *func_glGetTexLevelParameteriv_t) (GLenum target,  GLint level,  GLenum pname,  GLint *params);
typedef void ( WINAPI *func_glGetTexParameterfv_t) (GLenum target,  GLenum pname,  GLfloat *params);
typedef void ( WINAPI *func_glGetTexParameteriv_t) (GLenum target,  GLenum pname,  GLint *params);
typedef void ( WINAPI *func_glHint_t) (GLenum target,  GLenum mode);
typedef void ( WINAPI *func_glIndexMask_t) (GLuint mask);
typedef void ( WINAPI *func_glIndexPointer_t) (GLenum type,  GLsizei stride,  const GLvoid *pointer);
typedef void ( WINAPI *func_glIndexd_t) (GLdouble c);
typedef void ( WINAPI *func_glIndexdv_t) (const GLdouble *c);
typedef void ( WINAPI *func_glIndexf_t) (GLfloat c);
typedef void ( WINAPI *func_glIndexfv_t) (const GLfloat *c);
typedef void ( WINAPI *func_glIndexi_t) (GLint c);
typedef void ( WINAPI *func_glIndexiv_t) (const GLint *c);
typedef void ( WINAPI *func_glIndexs_t) (GLshort c);
typedef void ( WINAPI *func_glIndexsv_t) (const GLshort *c);
typedef void ( WINAPI *func_glIndexub_t) (GLubyte c);
typedef void ( WINAPI *func_glIndexubv_t) (const GLubyte *c);
typedef void ( WINAPI *func_glInitNames_t) (void);
typedef void ( WINAPI *func_glInterleavedArrays_t) (GLenum format,  GLsizei stride,  const GLvoid *pointer);
typedef GLboolean ( WINAPI *func_glIsEnabled_t) (GLenum cap);
typedef GLboolean ( WINAPI *func_glIsList_t) (GLuint list);
typedef GLboolean ( WINAPI *func_glIsTexture_t) (GLuint texture);
typedef void ( WINAPI *func_glLightModelf_t) (GLenum pname,  GLfloat param);
typedef void ( WINAPI *func_glLightModelfv_t) (GLenum pname,  const GLfloat *params);
typedef void ( WINAPI *func_glLightModeli_t) (GLenum pname,  GLint param);
typedef void ( WINAPI *func_glLightModeliv_t) (GLenum pname,  const GLint *params);
typedef void ( WINAPI *func_glLightf_t) (GLenum light,  GLenum pname,  GLfloat param);
typedef void ( WINAPI *func_glLightfv_t) (GLenum light,  GLenum pname,  const GLfloat *params);
typedef void ( WINAPI *func_glLighti_t) (GLenum light,  GLenum pname,  GLint param);
typedef void ( WINAPI *func_glLightiv_t) (GLenum light,  GLenum pname,  const GLint *params);
typedef void ( WINAPI *func_glLineStipple_t) (GLint factor,  GLushort pattern);
typedef void ( WINAPI *func_glLineWidth_t) (GLfloat width);
typedef void ( WINAPI *func_glListBase_t) (GLuint base);
typedef void ( WINAPI *func_glLoadIdentity_t) (void);
typedef void ( WINAPI *func_glLoadMatrixd_t) (const GLdouble *m);
typedef void ( WINAPI *func_glLoadMatrixf_t) (const GLfloat *m);
typedef void ( WINAPI *func_glLoadName_t) (GLuint name);
typedef void ( WINAPI *func_glLogicOp_t) (GLenum opcode);
typedef void ( WINAPI *func_glMap1d_t) (GLenum target,  GLdouble u1,  GLdouble u2,  GLint stride,  GLint order,  const GLdouble *points);
typedef void ( WINAPI *func_glMap1f_t) (GLenum target,  GLfloat u1,  GLfloat u2,  GLint stride,  GLint order,  const GLfloat *points);
typedef void ( WINAPI *func_glMap2d_t) (GLenum target,  GLdouble u1,  GLdouble u2,  GLint ustride,  GLint uorder,  GLdouble v1,  GLdouble v2,  GLint vstride,  GLint vorder,  const GLdouble *points);
typedef void ( WINAPI *func_glMap2f_t) (GLenum target,  GLfloat u1,  GLfloat u2,  GLint ustride,  GLint uorder,  GLfloat v1,  GLfloat v2,  GLint vstride,  GLint vorder,  const GLfloat *points);
typedef void ( WINAPI *func_glMapGrid1d_t) (GLint un,  GLdouble u1,  GLdouble u2);
typedef void ( WINAPI *func_glMapGrid1f_t) (GLint un,  GLfloat u1,  GLfloat u2);
typedef void ( WINAPI *func_glMapGrid2d_t) (GLint un,  GLdouble u1,  GLdouble u2,  GLint vn,  GLdouble v1,  GLdouble v2);
typedef void ( WINAPI *func_glMapGrid2f_t) (GLint un,  GLfloat u1,  GLfloat u2,  GLint vn,  GLfloat v1,  GLfloat v2);
typedef void ( WINAPI *func_glMaterialf_t) (GLenum face,  GLenum pname,  GLfloat param);
typedef void ( WINAPI *func_glMaterialfv_t) (GLenum face,  GLenum pname,  const GLfloat *params);
typedef void ( WINAPI *func_glMateriali_t) (GLenum face,  GLenum pname,  GLint param);
typedef void ( WINAPI *func_glMaterialiv_t) (GLenum face,  GLenum pname,  const GLint *params);
typedef void ( WINAPI *func_glMatrixMode_t) (GLenum mode);
typedef void ( WINAPI *func_glMultMatrixd_t) (const GLdouble *m);
typedef void ( WINAPI *func_glMultMatrixf_t) (const GLfloat *m);
typedef void ( WINAPI *func_glNewList_t) (GLuint list,  GLenum mode);
typedef void ( WINAPI *func_glNormal3b_t) (GLbyte nx,  GLbyte ny,  GLbyte nz);
typedef void ( WINAPI *func_glNormal3bv_t) (const GLbyte *v);
typedef void ( WINAPI *func_glNormal3d_t) (GLdouble nx,  GLdouble ny,  GLdouble nz);
typedef void ( WINAPI *func_glNormal3dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glNormal3f_t) (GLfloat nx,  GLfloat ny,  GLfloat nz);
typedef void ( WINAPI *func_glNormal3fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glNormal3i_t) (GLint nx,  GLint ny,  GLint nz);
typedef void ( WINAPI *func_glNormal3iv_t) (const GLint *v);
typedef void ( WINAPI *func_glNormal3s_t) (GLshort nx,  GLshort ny,  GLshort nz);
typedef void ( WINAPI *func_glNormal3sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glNormalPointer_t) (GLenum type,  GLsizei stride,  const GLvoid *pointer);
typedef void ( WINAPI *func_glOrtho_t) (GLdouble left,  GLdouble right,  GLdouble bottom,  GLdouble top,  GLdouble zNear,  GLdouble zFar);
typedef void ( WINAPI *func_glPassThrough_t) (GLfloat token);
typedef void ( WINAPI *func_glPixelMapfv_t) (GLenum map,  GLsizei mapsize,  const GLfloat *values);
typedef void ( WINAPI *func_glPixelMapuiv_t) (GLenum map,  GLsizei mapsize,  const GLuint *values);
typedef void ( WINAPI *func_glPixelMapusv_t) (GLenum map,  GLsizei mapsize,  const GLushort *values);
typedef void ( WINAPI *func_glPixelStoref_t) (GLenum pname,  GLfloat param);
typedef void ( WINAPI *func_glPixelStorei_t) (GLenum pname,  GLint param);
typedef void ( WINAPI *func_glPixelTransferf_t) (GLenum pname,  GLfloat param);
typedef void ( WINAPI *func_glPixelTransferi_t) (GLenum pname,  GLint param);
typedef void ( WINAPI *func_glPixelZoom_t) (GLfloat xfactor,  GLfloat yfactor);
typedef void ( WINAPI *func_glPointSize_t) (GLfloat size);
typedef void ( WINAPI *func_glPolygonMode_t) (GLenum face,  GLenum mode);
typedef void ( WINAPI *func_glPolygonOffset_t) (GLfloat factor,  GLfloat units);
typedef void ( WINAPI *func_glPolygonStipple_t) (const GLubyte *mask);
typedef void ( WINAPI *func_glPopAttrib_t) (void);
typedef void ( WINAPI *func_glPopClientAttrib_t) (void);
typedef void ( WINAPI *func_glPopMatrix_t) (void);
typedef void ( WINAPI *func_glPopName_t) (void);
typedef void ( WINAPI *func_glPrioritizeTextures_t) (GLsizei n,  const GLuint *textures,  const GLclampf *priorities);
typedef void ( WINAPI *func_glPushAttrib_t) (GLbitfield mask);
typedef void ( WINAPI *func_glPushClientAttrib_t) (GLbitfield mask);
typedef void ( WINAPI *func_glPushMatrix_t) (void);
typedef void ( WINAPI *func_glPushName_t) (GLuint name);
typedef void ( WINAPI *func_glRasterPos2d_t) (GLdouble x,  GLdouble y);
typedef void ( WINAPI *func_glRasterPos2dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glRasterPos2f_t) (GLfloat x,  GLfloat y);
typedef void ( WINAPI *func_glRasterPos2fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glRasterPos2i_t) (GLint x,  GLint y);
typedef void ( WINAPI *func_glRasterPos2iv_t) (const GLint *v);
typedef void ( WINAPI *func_glRasterPos2s_t) (GLshort x,  GLshort y);
typedef void ( WINAPI *func_glRasterPos2sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glRasterPos3d_t) (GLdouble x,  GLdouble y,  GLdouble z);
typedef void ( WINAPI *func_glRasterPos3dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glRasterPos3f_t) (GLfloat x,  GLfloat y,  GLfloat z);
typedef void ( WINAPI *func_glRasterPos3fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glRasterPos3i_t) (GLint x,  GLint y,  GLint z);
typedef void ( WINAPI *func_glRasterPos3iv_t) (const GLint *v);
typedef void ( WINAPI *func_glRasterPos3s_t) (GLshort x,  GLshort y,  GLshort z);
typedef void ( WINAPI *func_glRasterPos3sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glRasterPos4d_t) (GLdouble x,  GLdouble y,  GLdouble z,  GLdouble w);
typedef void ( WINAPI *func_glRasterPos4dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glRasterPos4f_t) (GLfloat x,  GLfloat y,  GLfloat z,  GLfloat w);
typedef void ( WINAPI *func_glRasterPos4fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glRasterPos4i_t) (GLint x,  GLint y,  GLint z,  GLint w);
typedef void ( WINAPI *func_glRasterPos4iv_t) (const GLint *v);
typedef void ( WINAPI *func_glRasterPos4s_t) (GLshort x,  GLshort y,  GLshort z,  GLshort w);
typedef void ( WINAPI *func_glRasterPos4sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glReadBuffer_t) (GLenum mode);
typedef void ( WINAPI *func_glReadPixels_t) (GLint x,  GLint y,  GLsizei width,  GLsizei height,  GLenum format,  GLenum type,  GLvoid *pixels);
typedef void ( WINAPI *func_glRectd_t) (GLdouble x1,  GLdouble y1,  GLdouble x2,  GLdouble y2);
typedef void ( WINAPI *func_glRectdv_t) (const GLdouble *v1,  const GLdouble *v2);
typedef void ( WINAPI *func_glRectf_t) (GLfloat x1,  GLfloat y1,  GLfloat x2,  GLfloat y2);
typedef void ( WINAPI *func_glRectfv_t) (const GLfloat *v1,  const GLfloat *v2);
typedef void ( WINAPI *func_glRecti_t) (GLint x1,  GLint y1,  GLint x2,  GLint y2);
typedef void ( WINAPI *func_glRectiv_t) (const GLint *v1,  const GLint *v2);
typedef void ( WINAPI *func_glRects_t) (GLshort x1,  GLshort y1,  GLshort x2,  GLshort y2);
typedef void ( WINAPI *func_glRectsv_t) (const GLshort *v1,  const GLshort *v2);
typedef GLint ( WINAPI *func_glRenderMode_t) (GLenum mode);
typedef void ( WINAPI *func_glRotated_t) (GLdouble angle,  GLdouble x,  GLdouble y,  GLdouble z);
typedef void ( WINAPI *func_glRotatef_t) (GLfloat angle,  GLfloat x,  GLfloat y,  GLfloat z);
typedef void ( WINAPI *func_glScaled_t) (GLdouble x,  GLdouble y,  GLdouble z);
typedef void ( WINAPI *func_glScalef_t) (GLfloat x,  GLfloat y,  GLfloat z);
typedef void ( WINAPI *func_glScissor_t) (GLint x,  GLint y,  GLsizei width,  GLsizei height);
typedef void ( WINAPI *func_glSelectBuffer_t) (GLsizei size,  GLuint *buffer);
typedef void ( WINAPI *func_glShadeModel_t) (GLenum mode);
typedef void ( WINAPI *func_glStencilFunc_t) (GLenum func,  GLint ref,  GLuint mask);
typedef void ( WINAPI *func_glStencilMask_t) (GLuint mask);
typedef void ( WINAPI *func_glStencilOp_t) (GLenum fail,  GLenum zfail,  GLenum zpass);
typedef void ( WINAPI *func_glSwapBuffers_t) (void);
typedef void ( WINAPI *func_glTexCoord1d_t) (GLdouble s);
typedef void ( WINAPI *func_glTexCoord1dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glTexCoord1f_t) (GLfloat s);
typedef void ( WINAPI *func_glTexCoord1fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glTexCoord1i_t) (GLint s);
typedef void ( WINAPI *func_glTexCoord1iv_t) (const GLint *v);
typedef void ( WINAPI *func_glTexCoord1s_t) (GLshort s);
typedef void ( WINAPI *func_glTexCoord1sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glTexCoord2d_t) (GLdouble s,  GLdouble t);
typedef void ( WINAPI *func_glTexCoord2dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glTexCoord2f_t) (GLfloat s,  GLfloat t);
typedef void ( WINAPI *func_glTexCoord2fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glTexCoord2i_t) (GLint s,  GLint t);
typedef void ( WINAPI *func_glTexCoord2iv_t) (const GLint *v);
typedef void ( WINAPI *func_glTexCoord2s_t) (GLshort s,  GLshort t);
typedef void ( WINAPI *func_glTexCoord2sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glTexCoord3d_t) (GLdouble s,  GLdouble t,  GLdouble r);
typedef void ( WINAPI *func_glTexCoord3dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glTexCoord3f_t) (GLfloat s,  GLfloat t,  GLfloat r);
typedef void ( WINAPI *func_glTexCoord3fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glTexCoord3i_t) (GLint s,  GLint t,  GLint r);
typedef void ( WINAPI *func_glTexCoord3iv_t) (const GLint *v);
typedef void ( WINAPI *func_glTexCoord3s_t) (GLshort s,  GLshort t,  GLshort r);
typedef void ( WINAPI *func_glTexCoord3sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glTexCoord4d_t) (GLdouble s,  GLdouble t,  GLdouble r,  GLdouble q);
typedef void ( WINAPI *func_glTexCoord4dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glTexCoord4f_t) (GLfloat s,  GLfloat t,  GLfloat r,  GLfloat q);
typedef void ( WINAPI *func_glTexCoord4fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glTexCoord4i_t) (GLint s,  GLint t,  GLint r,  GLint q);
typedef void ( WINAPI *func_glTexCoord4iv_t) (const GLint *v);
typedef void ( WINAPI *func_glTexCoord4s_t) (GLshort s,  GLshort t,  GLshort r,  GLshort q);
typedef void ( WINAPI *func_glTexCoord4sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glTexCoordPointer_t) (GLint size,  GLenum type,  GLsizei stride,  const GLvoid *pointer);
typedef void ( WINAPI *func_glTexEnvf_t) (GLenum target,  GLenum pname,  GLfloat param);
typedef void ( WINAPI *func_glTexEnvfv_t) (GLenum target,  GLenum pname,  const GLfloat *params);
typedef void ( WINAPI *func_glTexEnvi_t) (GLenum target,  GLenum pname,  GLint param);
typedef void ( WINAPI *func_glTexEnviv_t) (GLenum target,  GLenum pname,  const GLint *params);
typedef void ( WINAPI *func_glTexGend_t) (GLenum coord,  GLenum pname,  GLdouble param);
typedef void ( WINAPI *func_glTexGendv_t) (GLenum coord,  GLenum pname,  const GLdouble *params);
typedef void ( WINAPI *func_glTexGenf_t) (GLenum coord,  GLenum pname,  GLfloat param);
typedef void ( WINAPI *func_glTexGenfv_t) (GLenum coord,  GLenum pname,  const GLfloat *params);
typedef void ( WINAPI *func_glTexGeni_t) (GLenum coord,  GLenum pname,  GLint param);
typedef void ( WINAPI *func_glTexGeniv_t) (GLenum coord,  GLenum pname,  const GLint *params);
typedef void ( WINAPI *func_glTexImage1D_t) (GLenum target,  GLint level,  GLint internalformat,  GLsizei width,  GLint border,  GLenum format,  GLenum type,  const GLvoid *pixels);
typedef void ( WINAPI *func_glTexImage2D_t) (GLenum target,  GLint level,  GLint internalformat,  GLsizei width,  GLsizei height,  GLint border,  GLenum format,  GLenum type,  const GLvoid *pixels);
typedef void ( WINAPI *func_glTexParameterf_t) (GLenum target,  GLenum pname,  GLfloat param);
typedef void ( WINAPI *func_glTexParameterfv_t) (GLenum target,  GLenum pname,  const GLfloat *params);
typedef void ( WINAPI *func_glTexParameteri_t) (GLenum target,  GLenum pname,  GLint param);
typedef void ( WINAPI *func_glTexParameteriv_t) (GLenum target,  GLenum pname,  const GLint *params);
typedef void ( WINAPI *func_glTexSubImage1D_t) (GLenum target,  GLint level,  GLint xoffset,  GLsizei width,  GLenum format,  GLenum type,  const GLvoid *pixels);
typedef void ( WINAPI *func_glTexSubImage2D_t) (GLenum target,  GLint level,  GLint xoffset,  GLint yoffset,  GLsizei width,  GLsizei height,  GLenum format,  GLenum type,  const GLvoid *pixels);
typedef void ( WINAPI *func_glTranslated_t) (GLdouble x,  GLdouble y,  GLdouble z);
typedef void ( WINAPI *func_glTranslatef_t) (GLfloat x,  GLfloat y,  GLfloat z);
typedef void ( WINAPI *func_glVertex2d_t) (GLdouble x,  GLdouble y);
typedef void ( WINAPI *func_glVertex2dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glVertex2f_t) (GLfloat x,  GLfloat y);
typedef void ( WINAPI *func_glVertex2fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glVertex2i_t) (GLint x,  GLint y);
typedef void ( WINAPI *func_glVertex2iv_t) (const GLint *v);
typedef void ( WINAPI *func_glVertex2s_t) (GLshort x,  GLshort y);
typedef void ( WINAPI *func_glVertex2sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glVertex3d_t) (GLdouble x,  GLdouble y,  GLdouble z);
typedef void ( WINAPI *func_glVertex3dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glVertex3f_t) (GLfloat x,  GLfloat y,  GLfloat z);
typedef void ( WINAPI *func_glVertex3fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glVertex3i_t) (GLint x,  GLint y,  GLint z);
typedef void ( WINAPI *func_glVertex3iv_t) (const GLint *v);
typedef void ( WINAPI *func_glVertex3s_t) (GLshort x,  GLshort y,  GLshort z);
typedef void ( WINAPI *func_glVertex3sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glVertex4d_t) (GLdouble x,  GLdouble y,  GLdouble z,  GLdouble w);
typedef void ( WINAPI *func_glVertex4dv_t) (const GLdouble *v);
typedef void ( WINAPI *func_glVertex4f_t) (GLfloat x,  GLfloat y,  GLfloat z,  GLfloat w);
typedef void ( WINAPI *func_glVertex4fv_t) (const GLfloat *v);
typedef void ( WINAPI *func_glVertex4i_t) (GLint x,  GLint y,  GLint z,  GLint w);
typedef void ( WINAPI *func_glVertex4iv_t) (const GLint *v);
typedef void ( WINAPI *func_glVertex4s_t) (GLshort x,  GLshort y,  GLshort z,  GLshort w);
typedef void ( WINAPI *func_glVertex4sv_t) (const GLshort *v);
typedef void ( WINAPI *func_glVertexPointer_t) (GLint size,  GLenum type,  GLsizei stride,  const GLvoid *pointer);
typedef void ( WINAPI *func_glViewport_t) (GLint x,  GLint y,  GLsizei width,  GLsizei height);
typedef void ( WINAPI *func_wglChoosePixelFormat_t) (void);
typedef void ( WINAPI *func_wglCopyContext_t) (void);
typedef void ( WINAPI *func_wglCreateContext_t) (void);
typedef void ( WINAPI *func_wglCreateLayerContext_t) (void);
typedef void ( WINAPI *func_wglDeleteContext_t) (void);
typedef void ( WINAPI *func_wglDescribeLayerPlane_t) (void);
typedef void ( WINAPI *func_wglDescribePixelFormat_t) (void);
typedef void ( WINAPI *func_wglGetCurrentContext_t) (void);
typedef HDC  ( WINAPI *func_wglGetCurrentDC_t) (void);
typedef void ( WINAPI *func_wglGetDefaultProcAddress_t) (void);
typedef void ( WINAPI *func_wglGetLayerPaletteEntries_t) (void);
typedef void ( WINAPI *func_wglGetPixelFormat_t) (void);
typedef PROC ( WINAPI *func_wglGetProcAddress_t) (LPCSTR);
typedef void ( WINAPI *func_wglMakeCurrent_t) (void);
typedef void ( WINAPI *func_wglRealizeLayerPalette_t) (void);
typedef void ( WINAPI *func_wglSetLayerPaletteEntries_t) (void);
typedef void ( WINAPI *func_wglSetPixelFormat_t) (void);
typedef void ( WINAPI *func_wglShareLists_t) (void);
typedef void ( WINAPI *func_wglSwapBuffers_t) (HDC hDC);
typedef void ( WINAPI *func_wglSwapLayerBuffers_t) (void);
typedef void ( WINAPI *func_wglUseFontBitmapsA_t) (HDC, DWORD, DWORD, DWORD);
typedef void ( WINAPI *func_wglUseFontBitmapsW_t) (void);
typedef void ( WINAPI *func_wglUseFontOutlinesA_t) (HDC, DWORD, DWORD, DWORD, FLOAT, FLOAT, int, LPGLYPHMETRICSFLOAT);
typedef void ( WINAPI *func_wglUseFontOutlinesW_t) (void);

extern func_glActiveTextureARB_t orig_glActiveTextureARB;
extern func_BindTextureEXT_t orig_BindTextureEXT;
extern func_glMultiTexCoord2fARB_t orig_glMultiTexCoord2fARB;
extern func_glAccum_t	orig_glAccum;
extern func_glAlphaFunc_t	orig_glAlphaFunc;
extern func_glAreTexturesResident_t	orig_glAreTexturesResident;
extern func_glArrayElement_t	orig_glArrayElement;
extern func_glBegin_t	orig_glBegin;
extern func_glBindTexture_t	orig_glBindTexture;
extern func_glBitmap_t	orig_glBitmap;
extern func_glBlendFunc_t	orig_glBlendFunc;
extern func_glCallList_t	orig_glCallList;
extern func_glCallLists_t	orig_glCallLists;
extern func_glClear_t	orig_glClear;
extern func_glClearAccum_t	orig_glClearAccum;
extern func_glClearColor_t	orig_glClearColor;
extern func_glClearDepth_t	orig_glClearDepth;
extern func_glClearIndex_t	orig_glClearIndex;
extern func_glClearStencil_t	orig_glClearStencil;
extern func_glClipPlane_t	orig_glClipPlane;
extern func_glColor3b_t	orig_glColor3b;
extern func_glColor3bv_t	orig_glColor3bv;
extern func_glColor3d_t	orig_glColor3d;
extern func_glColor3dv_t	orig_glColor3dv;
extern func_glColor3f_t	orig_glColor3f;
extern func_glColor3fv_t	orig_glColor3fv;
extern func_glColor3i_t	orig_glColor3i;
extern func_glColor3iv_t	orig_glColor3iv;
extern func_glColor3s_t	orig_glColor3s;
extern func_glColor3sv_t	orig_glColor3sv;
extern func_glColor3ub_t	orig_glColor3ub;
extern func_glColor3ubv_t	orig_glColor3ubv;
extern func_glColor3ui_t	orig_glColor3ui;
extern func_glColor3uiv_t	orig_glColor3uiv;
extern func_glColor3us_t	orig_glColor3us;
extern func_glColor3usv_t	orig_glColor3usv;
extern func_glColor4b_t	orig_glColor4b;
extern func_glColor4bv_t	orig_glColor4bv;
extern func_glColor4d_t	orig_glColor4d;
extern func_glColor4dv_t	orig_glColor4dv;
extern func_glColor4f_t	orig_glColor4f;
extern func_glColor4fv_t	orig_glColor4fv;
extern func_glColor4i_t	orig_glColor4i;
extern func_glColor4iv_t	orig_glColor4iv;
extern func_glColor4s_t	orig_glColor4s;
extern func_glColor4sv_t	orig_glColor4sv;
extern func_glColor4ub_t	orig_glColor4ub;
extern func_glColor4ubv_t	orig_glColor4ubv;
extern func_glColor4ui_t	orig_glColor4ui;
extern func_glColor4uiv_t	orig_glColor4uiv;
extern func_glColor4us_t	orig_glColor4us;
extern func_glColor4usv_t	orig_glColor4usv;
extern func_glColorMask_t	orig_glColorMask;
extern func_glColorMaterial_t	orig_glColorMaterial;
extern func_glColorPointer_t	orig_glColorPointer;
extern func_glCopyPixels_t	orig_glCopyPixels;
extern func_glCopyTexImage1D_t	orig_glCopyTexImage1D;
extern func_glCopyTexImage2D_t	orig_glCopyTexImage2D;
extern func_glCopyTexSubImage1D_t	orig_glCopyTexSubImage1D;
extern func_glCopyTexSubImage2D_t	orig_glCopyTexSubImage2D;
extern func_glCullFace_t	orig_glCullFace;
extern func_glDebugEntry_t	orig_glDebugEntry;
extern func_glDeleteLists_t	orig_glDeleteLists;
extern func_glDeleteTextures_t	orig_glDeleteTextures;
extern func_glDepthFunc_t	orig_glDepthFunc;
extern func_glDepthMask_t	orig_glDepthMask;
extern func_glDepthRange_t	orig_glDepthRange;
extern func_glDisable_t	orig_glDisable;
extern func_glDisableClientState_t	orig_glDisableClientState;
extern func_glDrawArrays_t	orig_glDrawArrays;
extern func_glDrawBuffer_t	orig_glDrawBuffer;
extern func_glDrawElements_t	orig_glDrawElements;
extern func_glDrawPixels_t	orig_glDrawPixels;
extern func_glEdgeFlag_t	orig_glEdgeFlag;
extern func_glEdgeFlagPointer_t	orig_glEdgeFlagPointer;
extern func_glEdgeFlagv_t	orig_glEdgeFlagv;
extern func_glEnable_t	orig_glEnable;
extern func_glEnableClientState_t	orig_glEnableClientState;
extern func_glEnd_t	orig_glEnd;
extern func_glEndList_t	orig_glEndList;
extern func_glEvalCoord1d_t	orig_glEvalCoord1d;
extern func_glEvalCoord1dv_t	orig_glEvalCoord1dv;
extern func_glEvalCoord1f_t	orig_glEvalCoord1f;
extern func_glEvalCoord1fv_t	orig_glEvalCoord1fv;
extern func_glEvalCoord2d_t	orig_glEvalCoord2d;
extern func_glEvalCoord2dv_t	orig_glEvalCoord2dv;
extern func_glEvalCoord2f_t	orig_glEvalCoord2f;
extern func_glEvalCoord2fv_t	orig_glEvalCoord2fv;
extern func_glEvalMesh1_t	orig_glEvalMesh1;
extern func_glEvalMesh2_t	orig_glEvalMesh2;
extern func_glEvalPoint1_t	orig_glEvalPoint1;
extern func_glEvalPoint2_t	orig_glEvalPoint2;
extern func_glFeedbackBuffer_t	orig_glFeedbackBuffer;
extern func_glFinish_t	orig_glFinish;
extern func_glFlush_t	orig_glFlush;
extern func_glFogf_t	orig_glFogf;
extern func_glFogfv_t	orig_glFogfv;
extern func_glFogi_t	orig_glFogi;
extern func_glFogiv_t	orig_glFogiv;
extern func_glFrontFace_t	orig_glFrontFace;
extern func_glFrustum_t	orig_glFrustum;
extern func_glGenLists_t	orig_glGenLists;
extern func_glGenTextures_t	orig_glGenTextures;
extern func_glGetBooleanv_t	orig_glGetBooleanv;
extern func_glGetClipPlane_t	orig_glGetClipPlane;
extern func_glGetDoublev_t	orig_glGetDoublev;
extern func_glGetError_t	orig_glGetError;
extern func_glGetFloatv_t	orig_glGetFloatv;
extern func_glGetIntegerv_t	orig_glGetIntegerv;
extern func_glGetLightfv_t	orig_glGetLightfv;
extern func_glGetLightiv_t	orig_glGetLightiv;
extern func_glGetMapdv_t	orig_glGetMapdv;
extern func_glGetMapfv_t	orig_glGetMapfv;
extern func_glGetMapiv_t	orig_glGetMapiv;
extern func_glGetMaterialfv_t	orig_glGetMaterialfv;
extern func_glGetMaterialiv_t	orig_glGetMaterialiv;
extern func_glGetPixelMapfv_t	orig_glGetPixelMapfv;
extern func_glGetPixelMapuiv_t	orig_glGetPixelMapuiv;
extern func_glGetPixelMapusv_t	orig_glGetPixelMapusv;
extern func_glGetPointerv_t	orig_glGetPointerv;
extern func_glGetPolygonStipple_t	orig_glGetPolygonStipple;
extern func_glGetString_t	orig_glGetString;
extern func_glGetTexEnvfv_t	orig_glGetTexEnvfv;
extern func_glGetTexEnviv_t	orig_glGetTexEnviv;
extern func_glGetTexGendv_t	orig_glGetTexGendv;
extern func_glGetTexGenfv_t	orig_glGetTexGenfv;
extern func_glGetTexGeniv_t	orig_glGetTexGeniv;
extern func_glGetTexImage_t	orig_glGetTexImage;
extern func_glGetTexLevelParameterfv_t	orig_glGetTexLevelParameterfv;
extern func_glGetTexLevelParameteriv_t	orig_glGetTexLevelParameteriv;
extern func_glGetTexParameterfv_t	orig_glGetTexParameterfv;
extern func_glGetTexParameteriv_t	orig_glGetTexParameteriv;
extern func_glHint_t	orig_glHint;
extern func_glIndexMask_t	orig_glIndexMask;
extern func_glIndexPointer_t	orig_glIndexPointer;
extern func_glIndexd_t	orig_glIndexd;
extern func_glIndexdv_t	orig_glIndexdv;
extern func_glIndexf_t	orig_glIndexf;
extern func_glIndexfv_t	orig_glIndexfv;
extern func_glIndexi_t	orig_glIndexi;
extern func_glIndexiv_t	orig_glIndexiv;
extern func_glIndexs_t	orig_glIndexs;
extern func_glIndexsv_t	orig_glIndexsv;
extern func_glIndexub_t	orig_glIndexub;
extern func_glIndexubv_t	orig_glIndexubv;
extern func_glInitNames_t	orig_glInitNames;
extern func_glInterleavedArrays_t	orig_glInterleavedArrays;
extern func_glIsEnabled_t	orig_glIsEnabled;
extern func_glIsList_t	orig_glIsList;
extern func_glIsTexture_t	orig_glIsTexture;
extern func_glLightModelf_t	orig_glLightModelf;
extern func_glLightModelfv_t	orig_glLightModelfv;
extern func_glLightModeli_t	orig_glLightModeli;
extern func_glLightModeliv_t	orig_glLightModeliv;
extern func_glLightf_t	orig_glLightf;
extern func_glLightfv_t	orig_glLightfv;
extern func_glLighti_t	orig_glLighti;
extern func_glLightiv_t	orig_glLightiv;
extern func_glLineStipple_t	orig_glLineStipple;
extern func_glLineWidth_t	orig_glLineWidth;
extern func_glListBase_t	orig_glListBase;
extern func_glLoadIdentity_t	orig_glLoadIdentity;
extern func_glLoadMatrixd_t	orig_glLoadMatrixd;
extern func_glLoadMatrixf_t	orig_glLoadMatrixf;
extern func_glLoadName_t	orig_glLoadName;
extern func_glLogicOp_t	orig_glLogicOp;
extern func_glMap1d_t	orig_glMap1d;
extern func_glMap1f_t	orig_glMap1f;
extern func_glMap2d_t	orig_glMap2d;
extern func_glMap2f_t	orig_glMap2f;
extern func_glMapGrid1d_t	orig_glMapGrid1d;
extern func_glMapGrid1f_t	orig_glMapGrid1f;
extern func_glMapGrid2d_t	orig_glMapGrid2d;
extern func_glMapGrid2f_t	orig_glMapGrid2f;
extern func_glMaterialf_t	orig_glMaterialf;
extern func_glMaterialfv_t	orig_glMaterialfv;
extern func_glMateriali_t	orig_glMateriali;
extern func_glMaterialiv_t	orig_glMaterialiv;
extern func_glMatrixMode_t	orig_glMatrixMode;
extern func_glMultMatrixd_t	orig_glMultMatrixd;
extern func_glMultMatrixf_t	orig_glMultMatrixf;
extern func_glNewList_t	orig_glNewList;
extern func_glNormal3b_t	orig_glNormal3b;
extern func_glNormal3bv_t	orig_glNormal3bv;
extern func_glNormal3d_t	orig_glNormal3d;
extern func_glNormal3dv_t	orig_glNormal3dv;
extern func_glNormal3f_t	orig_glNormal3f;
extern func_glNormal3fv_t	orig_glNormal3fv;
extern func_glNormal3i_t	orig_glNormal3i;
extern func_glNormal3iv_t	orig_glNormal3iv;
extern func_glNormal3s_t	orig_glNormal3s;
extern func_glNormal3sv_t	orig_glNormal3sv;
extern func_glNormalPointer_t	orig_glNormalPointer;
extern func_glOrtho_t	orig_glOrtho;
extern func_glPassThrough_t	orig_glPassThrough;
extern func_glPixelMapfv_t	orig_glPixelMapfv;
extern func_glPixelMapuiv_t	orig_glPixelMapuiv;
extern func_glPixelMapusv_t	orig_glPixelMapusv;
extern func_glPixelStoref_t	orig_glPixelStoref;
extern func_glPixelStorei_t	orig_glPixelStorei;
extern func_glPixelTransferf_t	orig_glPixelTransferf;
extern func_glPixelTransferi_t	orig_glPixelTransferi;
extern func_glPixelZoom_t	orig_glPixelZoom;
extern func_glPointSize_t	orig_glPointSize;
extern func_glPolygonMode_t	orig_glPolygonMode;
extern func_glPolygonOffset_t	orig_glPolygonOffset;
extern func_glPolygonStipple_t	orig_glPolygonStipple;
extern func_glPopAttrib_t	orig_glPopAttrib;
extern func_glPopClientAttrib_t	orig_glPopClientAttrib;
extern func_glPopMatrix_t	orig_glPopMatrix;
extern func_glPopName_t	orig_glPopName;
extern func_glPrioritizeTextures_t	orig_glPrioritizeTextures;
extern func_glPushAttrib_t	orig_glPushAttrib;
extern func_glPushClientAttrib_t	orig_glPushClientAttrib;
extern func_glPushMatrix_t	orig_glPushMatrix;
extern func_glPushName_t	orig_glPushName;
extern func_glRasterPos2d_t	orig_glRasterPos2d;
extern func_glRasterPos2dv_t	orig_glRasterPos2dv;
extern func_glRasterPos2f_t	orig_glRasterPos2f;
extern func_glRasterPos2fv_t	orig_glRasterPos2fv;
extern func_glRasterPos2i_t	orig_glRasterPos2i;
extern func_glRasterPos2iv_t	orig_glRasterPos2iv;
extern func_glRasterPos2s_t	orig_glRasterPos2s;
extern func_glRasterPos2sv_t	orig_glRasterPos2sv;
extern func_glRasterPos3d_t	orig_glRasterPos3d;
extern func_glRasterPos3dv_t	orig_glRasterPos3dv;
extern func_glRasterPos3f_t	orig_glRasterPos3f;
extern func_glRasterPos3fv_t	orig_glRasterPos3fv;
extern func_glRasterPos3i_t	orig_glRasterPos3i;
extern func_glRasterPos3iv_t	orig_glRasterPos3iv;
extern func_glRasterPos3s_t	orig_glRasterPos3s;
extern func_glRasterPos3sv_t	orig_glRasterPos3sv;
extern func_glRasterPos4d_t	orig_glRasterPos4d;
extern func_glRasterPos4dv_t	orig_glRasterPos4dv;
extern func_glRasterPos4f_t	orig_glRasterPos4f;
extern func_glRasterPos4fv_t	orig_glRasterPos4fv;
extern func_glRasterPos4i_t	orig_glRasterPos4i;
extern func_glRasterPos4iv_t	orig_glRasterPos4iv;
extern func_glRasterPos4s_t	orig_glRasterPos4s;
extern func_glRasterPos4sv_t	orig_glRasterPos4sv;
extern func_glReadBuffer_t	orig_glReadBuffer;
extern func_glReadPixels_t	orig_glReadPixels;
extern func_glRectd_t	orig_glRectd;
extern func_glRectdv_t	orig_glRectdv;
extern func_glRectf_t	orig_glRectf;
extern func_glRectfv_t	orig_glRectfv;
extern func_glRecti_t	orig_glRecti;
extern func_glRectiv_t	orig_glRectiv;
extern func_glRects_t	orig_glRects;
extern func_glRectsv_t	orig_glRectsv;
extern func_glRenderMode_t	orig_glRenderMode;
extern func_glRotated_t	orig_glRotated;
extern func_glRotatef_t	orig_glRotatef;
extern func_glScaled_t	orig_glScaled;
extern func_glScalef_t	orig_glScalef;
extern func_glScissor_t	orig_glScissor;
extern func_glSelectBuffer_t	orig_glSelectBuffer;
extern func_glShadeModel_t	orig_glShadeModel;
extern func_glStencilFunc_t	orig_glStencilFunc;
extern func_glStencilMask_t	orig_glStencilMask;
extern func_glStencilOp_t	orig_glStencilOp;
extern func_glSwapBuffers_t	orig_glSwapBuffers;
extern func_glTexCoord1d_t	orig_glTexCoord1d;
extern func_glTexCoord1dv_t	orig_glTexCoord1dv;
extern func_glTexCoord1f_t	orig_glTexCoord1f;
extern func_glTexCoord1fv_t	orig_glTexCoord1fv;
extern func_glTexCoord1i_t	orig_glTexCoord1i;
extern func_glTexCoord1iv_t	orig_glTexCoord1iv;
extern func_glTexCoord1s_t	orig_glTexCoord1s;
extern func_glTexCoord1sv_t	orig_glTexCoord1sv;
extern func_glTexCoord2d_t	orig_glTexCoord2d;
extern func_glTexCoord2dv_t	orig_glTexCoord2dv;
extern func_glTexCoord2f_t	orig_glTexCoord2f;
extern func_glTexCoord2fv_t	orig_glTexCoord2fv;
extern func_glTexCoord2i_t	orig_glTexCoord2i;
extern func_glTexCoord2iv_t	orig_glTexCoord2iv;
extern func_glTexCoord2s_t	orig_glTexCoord2s;
extern func_glTexCoord2sv_t	orig_glTexCoord2sv;
extern func_glTexCoord3d_t	orig_glTexCoord3d;
extern func_glTexCoord3dv_t	orig_glTexCoord3dv;
extern func_glTexCoord3f_t	orig_glTexCoord3f;
extern func_glTexCoord3fv_t	orig_glTexCoord3fv;
extern func_glTexCoord3i_t	orig_glTexCoord3i;
extern func_glTexCoord3iv_t	orig_glTexCoord3iv;
extern func_glTexCoord3s_t	orig_glTexCoord3s;
extern func_glTexCoord3sv_t	orig_glTexCoord3sv;
extern func_glTexCoord4d_t	orig_glTexCoord4d;
extern func_glTexCoord4dv_t	orig_glTexCoord4dv;
extern func_glTexCoord4f_t	orig_glTexCoord4f;
extern func_glTexCoord4fv_t	orig_glTexCoord4fv;
extern func_glTexCoord4i_t	orig_glTexCoord4i;
extern func_glTexCoord4iv_t	orig_glTexCoord4iv;
extern func_glTexCoord4s_t	orig_glTexCoord4s;
extern func_glTexCoord4sv_t	orig_glTexCoord4sv;
extern func_glTexCoordPointer_t	orig_glTexCoordPointer;
extern func_glTexEnvf_t	orig_glTexEnvf;
extern func_glTexEnvfv_t	orig_glTexEnvfv;
extern func_glTexEnvi_t	orig_glTexEnvi;
extern func_glTexEnviv_t	orig_glTexEnviv;
extern func_glTexGend_t	orig_glTexGend;
extern func_glTexGendv_t	orig_glTexGendv;
extern func_glTexGenf_t	orig_glTexGenf;
extern func_glTexGenfv_t	orig_glTexGenfv;
extern func_glTexGeni_t	orig_glTexGeni;
extern func_glTexGeniv_t	orig_glTexGeniv;
extern func_glTexImage1D_t	orig_glTexImage1D;
extern func_glTexImage2D_t	orig_glTexImage2D;
extern func_glTexParameterf_t	orig_glTexParameterf;
extern func_glTexParameterfv_t	orig_glTexParameterfv;
extern func_glTexParameteri_t	orig_glTexParameteri;
extern func_glTexParameteriv_t	orig_glTexParameteriv;
extern func_glTexSubImage1D_t	orig_glTexSubImage1D;
extern func_glTexSubImage2D_t	orig_glTexSubImage2D;
extern func_glTranslated_t	orig_glTranslated;
extern func_glTranslatef_t	orig_glTranslatef;
extern func_glVertex2d_t	orig_glVertex2d;
extern func_glVertex2dv_t	orig_glVertex2dv;
extern func_glVertex2f_t	orig_glVertex2f;
extern func_glVertex2fv_t	orig_glVertex2fv;
extern func_glVertex2i_t	orig_glVertex2i;
extern func_glVertex2iv_t	orig_glVertex2iv;
extern func_glVertex2s_t	orig_glVertex2s;
extern func_glVertex2sv_t	orig_glVertex2sv;
extern func_glVertex3d_t	orig_glVertex3d;
extern func_glVertex3dv_t	orig_glVertex3dv;
extern func_glVertex3f_t	orig_glVertex3f;
extern func_glVertex3fv_t	orig_glVertex3fv;
extern func_glVertex3i_t	orig_glVertex3i;
extern func_glVertex3iv_t	orig_glVertex3iv;
extern func_glVertex3s_t	orig_glVertex3s;
extern func_glVertex3sv_t	orig_glVertex3sv;
extern func_glVertex4d_t	orig_glVertex4d;
extern func_glVertex4dv_t	orig_glVertex4dv;
extern func_glVertex4f_t	orig_glVertex4f;
extern func_glVertex4fv_t	orig_glVertex4fv;
extern func_glVertex4i_t	orig_glVertex4i;
extern func_glVertex4iv_t	orig_glVertex4iv;
extern func_glVertex4s_t	orig_glVertex4s;
extern func_glVertex4sv_t	orig_glVertex4sv;
extern func_glVertexPointer_t	orig_glVertexPointer;
extern func_glViewport_t	orig_glViewport;
extern func_wglChoosePixelFormat_t	orig_wglChoosePixelFormat;
extern func_wglCopyContext_t	orig_wglCopyContext;
extern func_wglCreateContext_t	orig_wglCreateContext;
extern func_wglCreateLayerContext_t	orig_wglCreateLayerContext;
extern func_wglDeleteContext_t	orig_wglDeleteContext;
extern func_wglDescribeLayerPlane_t	orig_wglDescribeLayerPlane;
extern func_wglDescribePixelFormat_t	orig_wglDescribePixelFormat;
extern func_wglGetCurrentContext_t	orig_wglGetCurrentContext;
extern func_wglGetCurrentDC_t	orig_wglGetCurrentDC;
extern func_wglGetDefaultProcAddress_t	orig_wglGetDefaultProcAddress;
extern func_wglGetLayerPaletteEntries_t	orig_wglGetLayerPaletteEntries;
extern func_wglGetPixelFormat_t	orig_wglGetPixelFormat;
extern func_wglGetProcAddress_t	orig_wglGetProcAddress;
extern func_wglMakeCurrent_t	orig_wglMakeCurrent;
extern func_wglRealizeLayerPalette_t	orig_wglRealizeLayerPalette;
extern func_wglSetLayerPaletteEntries_t	orig_wglSetLayerPaletteEntries;
extern func_wglSetPixelFormat_t	orig_wglSetPixelFormat;
extern func_wglShareLists_t	orig_wglShareLists;
extern func_wglSwapBuffers_t	orig_wglSwapBuffers;
extern func_wglSwapLayerBuffers_t	orig_wglSwapLayerBuffers;
extern func_wglUseFontBitmapsA_t	orig_wglUseFontBitmapsA;
extern func_wglUseFontBitmapsW_t	orig_wglUseFontBitmapsW;
extern func_wglUseFontOutlinesA_t	orig_wglUseFontOutlinesA;
extern func_wglUseFontOutlinesW_t	orig_wglUseFontOutlinesW;

extern func_glBegin_t orig_exp_glBegin;
extern DWORD *exp_glBegin;
extern func_glDrawElements_t orig_exp_glDrawElements;
extern DWORD *exp_glDrawElements;
extern func_glViewport_t orig_exp_glViewport;
extern DWORD *exp_glViewport;

#ifdef __cplusplus
}
#endif

#endif
