set(INTERNAL_YAML_CPP_DIR ${SOURCE_DIR}/thirdparty/yaml-cpp)

set(YAML_CPP_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(YAML_CPP_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(YAML_CPP_BUILD_CONTRIB OFF CACHE BOOL "" FORCE)

add_subdirectory(${INTERNAL_YAML_CPP_DIR} yaml-cpp)

set_target_properties(yaml-cpp PROPERTIES POSITION_INDEPENDENT_CODE ON)