#line 1 "../../../code/globalcpp/parser/yyLexer.cpp"

#line 3 "../../../code/globalcpp/parser/yyLexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer yy_create_buffer

    #define yy_delete_buffer yy_delete_buffer

    #define yy_scan_buffer yy_scan_buffer

    #define yy_scan_string yy_scan_string

    #define yy_scan_bytes yy_scan_bytes

    #define yy_init_buffer yy_init_buffer

    #define yy_flush_buffer yy_flush_buffer

    #define yy_load_buffer_state yy_load_buffer_state

    #define yy_switch_to_buffer yy_switch_to_buffer

    #define yypush_buffer_state yypush_buffer_state

    #define yypop_buffer_state yypop_buffer_state

    #define yyensure_buffer_stack yyensure_buffer_stack

    #define yylex yylex

    #define yyrestart yyrestart

    #define yylex_init yylex_init

    #define yylex_init_extra yylex_init_extra

    #define yylex_destroy yylex_destroy

    #define yyget_debug yyget_debug

    #define yyset_debug yyset_debug

    #define yyget_extra yyget_extra

    #define yyset_extra yyset_extra

    #define yyget_in yyget_in

    #define yyset_in yyset_in

    #define yyget_out yyget_out

    #define yyset_out yyset_out

    #define yyget_leng yyget_leng

    #define yyget_text yyget_text

    #define yyget_lineno yyget_lineno

    #define yyset_lineno yyset_lineno

    #define yywrap yywrap

    #define yyalloc yyalloc

    #define yyrealloc yyrealloc

    #define yyfree yyfree

    #define yytext yytext

    #define yyleng yyleng

    #define yyin yyin

    #define yyout yyout

    #define yy_flex_debug yy_flex_debug

    #define yylineno yylineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[358] =
    {   0,
       14,   15,   23,   14,   15,   23,    8,    8,   93,   91,
       92,   15,   91,   92,   14,   92,   14,   91,   92,   15,
       91,   92,   73,   91,   92,   91,   92,   77,   91,   92,
       72,   91,   92,   63,   91,   92,   45,   91,   92,   32,
       91,   92,   33,   91,   92,   59,   91,   92,   52,   91,
       92,   76,   91,   92,   55,   90,   91,   92,   75,   81,
       90,   91,   92,   61,   90,   91,   92,   80,   81,   90,
       91,   92,   37,   91,   92,   39,   91,   92,   47,   91,
       92,   36,   91,   92,   48,   91,   92,   17,   91,   92,
       90,   91,   92,   90,   91,   92,   34,   91,   92,   90,

       91,   92,   35,   91,   92,   44,   91,   92,   90,   91,
       92,   90,   91,   92,   90,   91,   92,   90,   91,   92,
       90,   91,   92,   90,   91,   92,   90,   91,   92,   90,
       91,   92,   90,   91,   92,   90,   91,   92,   90,   91,
       92,   90,   91,   92,   90,   91,   92,   90,   91,   92,
       30,   91,   92,   43,   91,   92,   31,   91,   92,   74,
       91,   92,    4,   92,    3,   92,    4,   92,   92,   13,
       92,    8,   92,    8,   13,   92,   12,   13,   92,   10,
       13,   92,   12,   13,   92,   12,   13,   92,   15,   14,
       51,   46,   16,   64,   42,   69,    5,   60,   54,   53,

       55,   58,   90,   90,   56,   81,   90,   90,    1,    7,
       90,   62,   80,   81,   90,   38,   65,   49,   40,   50,
       67,   90,   90,    6,   70,   90,   90,   90,   22,   90,
       90,   90,   90,   90,   90,   18,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   71,   41,    2,    8,
       11,   12,   12,   12,   12,   58,   57,   90,    7,    7,
       90,   66,   68,   79,   90,   90,   90,   90,   90,   90,
       90,   90,   21,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   82,   90,   90,   11,   12,   81,   81,
       90,   78,   90,   90,   85,   90,   90,   90,   19,   90,

       90,   90,   23,   90,   90,   90,   90,   90,   90,   27,
       90,   29,   90,   90,   90,    9,   12,   86,   90,   83,
       90,   90,   90,   90,   24,   90,   25,   90,   26,   90,
       90,   90,   28,   90,   90,   20,   90,   90,   90,   90,
       90,   90,   84,   90,   90,   90,   90,   90,   90,   87,
       90,   89,   90,   90,   90,   88,   90
    } ;

static const flex_int16_t yy_accept[220] =
    {   0,
        1,    4,    7,    7,    7,    7,    7,    8,    9,    9,
        9,   10,   12,   15,   17,   20,   23,   26,   28,   31,
       34,   37,   40,   43,   46,   49,   52,   55,   59,   64,
       68,   73,   76,   79,   82,   85,   88,   91,   94,   97,
      100,  103,  106,  109,  112,  115,  118,  121,  124,  127,
      130,  133,  136,  139,  142,  145,  148,  151,  154,  157,
      160,  163,  165,  167,  169,  170,  172,  174,  177,  180,
      183,  186,  189,  190,  191,  191,  192,  193,  193,  194,
      194,  195,  196,  197,  198,  199,  200,  201,  202,  204,
      205,  206,  208,  209,  210,  212,  213,  216,  217,  218,

      219,  220,  221,  222,  223,  224,  225,  226,  227,  228,
      229,  231,  232,  233,  234,  235,  236,  238,  239,  240,
      241,  242,  243,  244,  245,  246,  247,  248,  249,  250,
      251,  251,  253,  254,  254,  255,  256,  257,  258,  258,
      259,  260,  262,  263,  264,  266,  267,  268,  269,  270,
      271,  272,  273,  275,  276,  277,  278,  279,  280,  281,
      282,  283,  284,  286,  287,  288,  289,  290,  290,  292,
      294,  295,  297,  298,  299,  301,  302,  303,  305,  306,
      307,  308,  309,  310,  312,  314,  315,  316,  318,  320,
      322,  323,  324,  325,  327,  329,  331,  332,  333,  335,

      336,  338,  339,  340,  341,  342,  343,  345,  346,  347,
      348,  349,  350,  352,  354,  355,  356,  358,  358
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   28,   28,   28,   28,
       28,   28,   29,   28,   28,   30,   28,   31,   28,   28,
       28,   28,   28,   28,   32,   28,   28,   28,   28,   28,
       33,   34,   35,   36,   28,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   28,   46,   47,   48,   49,
       50,   51,   28,   52,   53,   54,   55,   56,   57,   28,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    2,    3,    1,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    5,
        1,    1,    1,    3,    1,    1,    5,    5,    5,    5,
        5,    5,    1,    3,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[225] =
    {   0,
        0,    0,   61,   62,    0,    0,   76,    0,    0,    0,
      331,  784,   64,   64,   67,  138,  232,  134,  784,  784,
      231,  133,  784,  784,  123,  130,  784,  141,  143,  145,
      155,  233,  784,   49,  228,  127,  784,  157,  161,  784,
      167,  784,  227,  171,  175,  177,  173,  178,  181,  182,
      189,  184,  183,  195,  193,  205,  187,  784,  153,  784,
      784,  784,  784,  230,  784,  784,  200,  212,  257,  784,
        0,  203,  233,  233,  231,  316,  784,  219,  784,  206,
      784,  784,  784,  784,  784,  784,  784,  784,  317,  318,
      784,  319,  321,  784,  360,  784,  419,  784,  150,  784,

      784,  784,  132,  320,  322,  238,  784,  323,  420,  421,
      324,  422,  423,  424,  429,  428,  325,  425,  426,  433,
      431,  430,  437,  427,  435,  459,  784,  784,  784,  240,
      498,    0,    0,  455,    0,   90,  784,  784,  314,  482,
        0,    0,  784,  784,  330,  461,  462,  466,  464,  507,
      491,  487,  489,  492,  553,  493,  554,  555,  557,  558,
      559,  560,  496,  562,  784,   33,  784,  230,  561,  563,
      564,  565,  568,  566,  569,  570,  571,  575,  592,  595,
      597,  600,  602,  608,  610,  612,  615,    0,  623,  624,
      625,  626,  628,  633,  635,  636,  640,  641,  648,  653,

      657,  658,  661,  662,  663,  664,  665,  666,  670,  671,
      686,  695,  678,  679,  696,  700,  701,  784,  758,  763,
      768,  771,  773,  778
    } ;

static const flex_int16_t yy_def[225] =
    {   0,
      218,    1,  219,  219,  220,  220,  218,    7,  220,  220,
      218,  218,  218,  218,  218,  218,  218,  221,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  222,  222,  222,
      222,  218,  218,  218,  218,  218,  218,  222,  222,  218,
      222,  218,  218,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      223,  223,  218,  218,  218,  218,  218,  221,  218,  221,
      218,  218,  218,  218,  218,  218,  218,  218,  222,  222,
      218,  222,  222,  218,  218,  218,  222,  218,  218,  218,

      218,  218,  218,  222,  222,  218,  218,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  218,  218,  218,  218,
       69,  223,   69,  131,  223,  223,  218,  218,  218,  222,
      224,   95,  218,  218,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  218,  223,  218,  218,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  223,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,    0,  218,  218,
      218,  218,  218,  218
    } ;

static const flex_int16_t yy_nxt[848] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   38,   38,   38,
       39,   38,   40,   41,   42,   43,   38,   44,   45,   46,
       47,   48,   49,   38,   50,   38,   51,   52,   38,   53,
       54,   38,   55,   56,   38,   38,   57,   38,   38,   58,
       59,   60,   61,   63,   63,   73,   74,   74,   73,   74,
       74,   99,  100,  188,   64,   64,   66,   66,   67,   68,
       66,   66,   69,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   70,   66,   71,   66,   66,   66,   66,

       66,   66,   71,   71,   71,   71,   71,   71,   66,   66,
       66,   66,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   72,   71,
       71,   71,   71,   71,   71,   66,   66,   66,   66,   73,
       79,   84,   73,   82,   86,   88,   85,  218,  166,  218,
      102,  103,   75,   87,   76,  144,   83,   89,   94,  218,
       92,  218,   92,   95,   91,  218,  218,   80,   96,  106,
      106,  218,   92,  143,   97,  218,  127,  218,  218,  218,
      218,  218,  218,   93,  218,  218,  218,  218,  218,  104,
      218,  218,  105,  218,  218,   93,  218,  218,  218,  218,

      218,  218,  130,  130,  218,  218,  218,  218,  218,  218,
      218,  109,  218,  128,  130,  130,  218,  115,  218,  112,
      120,  113,  108,  117,  110,   79,  111,  114,  218,  118,
      126,  122,  116,  123,   73,   74,   74,   73,  119,  121,
      106,  106,  130,  130,  139,   86,  139,  136,  129,  124,
      107,  101,   80,   98,   81,   77,  125,  131,  131,  131,
      131,  131,  131,  132,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  133,  131,  131,  131,
      131,  131,  131,  133,  133,  133,  133,  133,  133,  131,
      134,  131,  131,  133,  133,  133,  133,  133,  133,  133,

      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  131,  131,  131,  131,
       88,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  167,  137,  167,  218,  139,   92,  140,   92,  138,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  145,
      218,  146,  218,  218,  168,  218,  218,  218,  218,   93,
      141,  141,  218,  147,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  142,  142,  142,  142,
      141,  141,  141,  141,  141,  141,  142,  142,  142,  142,
      142,  142,  141,  142,  141,  141,  142,  142,  142,  142,

      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  141,
      141,  141,  141,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,   92,  218,   97,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,   93,
      218,  131,  152,  218,  157,  218,  218,  218,  218,  150,
      218,  162,  148,  149,  151,  153,  154,  155,  158,  159,
      156,  160,  218,  161,  218,  218,  218,  218,  131,  218,
      170,  218,  163,  218,  218,  218,  218,  218,  171,  169,

      218,  169,  173,  164,  165,  218,  172,  218,  218,  218,
      218,  218,  218,  176,  218,  218,  218,  131,  218,  218,
      218,  218,   93,  177,  131,  131,  131,  131,  131,  131,
      218,  175,  178,  180,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  218,  218,  218,
      174,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      181,  218,  218,  218,  218,  182,  218,  183,  218,  218,

      185,  218,  218,  218,  218,  184,  218,  179,  187,  189,
      191,  190,  218,  186,  218,  218,  218,  218,  218,  218,
      218,  192,  193,  218,  218,  218,  197,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  198,  218,  218,  218,
      218,  195,  194,  196,  218,  218,  218,  218,  218,  218,
      200,  218,  218,  199,  218,  201,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  202,  218,  218,  218,  203,  218,  204,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  205,  206,  218,  218,  218,  207,  209,  210,  218,

      218,  218,  218,  218,  218,  218,  213,  218,  218,  218,
      218,  218,  208,  218,  211,  212,  218,  218,  218,  218,
      218,  218,  215,  218,  218,  218,  218,  214,  214,  218,
      218,  216,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  217,  218,  218,  218,  217,   62,   62,
       62,   62,   62,   65,   65,   65,   65,   65,   78,   78,
       78,   78,   78,   90,  218,   90,  135,  135,  141,  218,
      141,  141,  141,   11,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218
    } ;

static const flex_int16_t yy_chk[848] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   13,   14,   14,   13,   15,
       15,   34,   34,  166,    3,    4,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,   16,
       18,   25,   16,   22,   26,   28,   25,   29,  136,   30,
       36,   36,   16,   26,   16,  103,   22,   28,   30,   31,
       29,   38,   29,   30,   28,   39,   29,   18,   30,   41,
       41,   41,   31,   99,   31,   44,   59,   47,   31,   45,
       38,   46,   48,   29,   39,   49,   50,   53,   52,   39,
       41,   57,   39,   51,   44,   31,   47,   55,   45,   54,

       46,   48,   67,   67,   49,   50,   53,   52,   80,   56,
       57,   45,   51,   59,   68,   68,   55,   49,   54,   47,
       52,   47,   44,   50,   45,   78,   46,   48,   56,   51,
       57,   54,   49,   55,   73,   74,   74,   73,   51,   53,
      106,  106,  130,  130,  168,   75,  168,   72,   64,   55,
       43,   35,   78,   32,   21,   17,   56,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       76,   89,   90,   92,  104,   93,  105,  108,  111,  117,
       11,  139,   76,  139,  145,   93,   92,   93,   92,   76,
       89,   90,   92,  104,   93,  105,  108,  111,  117,  104,
        0,  105,    0,  145,  139,    0,    0,    0,    0,   92,
       95,   95,    0,  108,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   97,  109,  110,  112,  113,  114,  118,
      119,  124,  116,  115,  122,  121,   97,  120,   97,  125,
        0,  123,   97,  109,  110,  112,  113,  114,  118,  119,
      124,  116,  115,  122,  121,    0,  120,  134,  125,   97,
      123,  134,  113,  126,  119,  146,  147,    0,  149,  110,
      148,  124,  109,  109,  112,  114,  115,  116,  120,  121,
      118,  122,  126,  123,  146,  147,  140,  149,  134,  148,
      146,  152,  125,  153,    0,  151,  154,  156,  147,  140,

      163,  140,  149,  126,  131,  140,  148,    0,    0,    0,
      152,  150,  153,  152,  151,  154,  156,  131,    0,  163,
        0,    0,  140,  152,  131,  131,  131,  131,  131,  131,
      150,  151,  154,  156,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  155,  157,  158,
      150,  159,  160,  161,  162,  169,  164,  170,  171,  172,
      174,    0,  173,  175,  176,  177,  155,  157,  158,  178,
      159,  160,  161,  162,  169,  164,  170,  171,  172,  174,
      157,  173,  175,  176,  177,  158,  179,  159,  178,  180,

      161,  181,    0,    0,  182,  160,  183,  155,  164,  171,
      174,  173,  184,  162,  185,  179,  186,    0,  180,  187,
      181,  176,  177,  182,    0,  183,  182,  189,  190,  191,
      192,  184,  193,  185,    0,  186,  182,  194,  187,  195,
      196,  180,  179,  181,  197,  198,  189,  190,  191,  192,
      186,  193,  199,  183,    0,  187,  194,  200,  195,  196,
        0,  201,  202,  197,  198,  203,  204,  205,  206,  207,
      208,  199,    0,  191,  209,  210,  200,  192,    0,  193,
      201,  202,  213,  214,  203,  204,  205,  206,  207,  208,
      211,  197,  198,  209,  210,    0,  200,  203,  204,  212,

      215,  213,  214,    0,  216,  217,  208,    0,    0,  211,
        0,    0,  202,    0,  205,  206,    0,    0,  212,  215,
        0,    0,  211,  216,  217,    0,    0,  209,  210,    0,
        0,  212,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  215,    0,    0,    0,  216,  219,  219,
      219,  219,  219,  220,  220,  220,  220,  220,  221,  221,
      221,  221,  221,  222,    0,  222,  223,  223,  224,    0,
      224,  224,  224,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[93] =
    {   0,
0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
#line 2 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
/*
* ===========================================================================
* Copyright (C) 2015 the OpenMoHAA team
* 
* This file is part of OpenMoHAA source code.
* 
* OpenMoHAA source code is free software; you can redistribute it
* and/or modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation; either version 2 of the License,
* or (at your option) any later version.
* 
* OpenMoHAA source code is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with OpenMoHAA source code; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
* ===========================================================================
*
*
* yyLexer.*: FLEX Lexical grammar for MoHScript.
*/

#include "compiler.h"
#include "yyParser.h"

#include <stdio.h>

void fprintf2( FILE *f, const char *format, ... )
{
	va_list va;
	static char buffer[ 4200 ];

	va_start( va, format );
	vsprintf( buffer, format, va );
	va_end( va );

	glbs.Printf( buffer );
}

#define fprintf fprintf2

int prev_yylex = 0;

extern yyparsedata parsedata;

#define YYLLOCSET { yylval.s.sourcePos = parsedata.pos - yyleng; }
#define YYLEX(n) { prev_yylex = n; return n; }

#define YY_USER_ACTION parsedata.pos; parsedata.pos += yyleng;
#define YY_FATAL_ERROR( n ) yylexerror( n )

void yylexerror( const char *msg )
{
	glbs.Printf( "%s\n%s", msg, yytext );
	assert( 0 );
}

static void TextEscapeValue( char *str, size_t len )
{
	char *to = parsetree_malloc( len + 1 );

	yylval.s.val.stringValue = to;

	while( len )
	{
		if( *str == '\\' )
		{
			len--;

			if( !len )
				break;

			str++;
			if( *str == 'n' )
			{
				*to = '\n';
			}
			else if( *str == 't' )
			{
				*to = '\t';
			}
			else if( *str == '"' )
			{
				*to = '\"';
			}
			else
			{
				*to = *str;
			}
		}
		else
		{
			*to = *str;
		}

		len--;
		str++;
		to++;
	}

	*to = 0;
}


static void TextValue( char *str, size_t len )
{
	yylval.s.val.stringValue = parsetree_malloc( len + 1 );
	strncpy( yylval.s.val.stringValue, str, len );
	yylval.s.val.stringValue[ len ] = 0;
}

static bool UseField( void )
{
	//return prev_yylex == TOKEN_PERIOD || prev_yylex == TOKEN_DOLLAR;
	return ( !strncmp( yytext, "game.", 5 ) ||
	!strncmp( yytext, "group.", 6 ) ||
	!strncmp( yytext, "level.", 6 ) ||
	!strncmp( yytext, "local.", 6 ) ||
	!strncmp( yytext, "parm.", 5 ) ||
	!strncmp( yytext, "owner.", 6 ) ||
	!strncmp( yytext, "self.", 5 ) ||
	*yytext == '$' || *yytext == '-' || *yytext == '/' );
}

#line 980 "../../../code/globalcpp/parser/yyLexer.cpp"
/*%option debug*/

#line 983 "../../../code/globalcpp/parser/yyLexer.cpp"

#define INITIAL 0
#define C_COMMENT 1
#define C_LINE_COMMENT 2
#define VARIABLES 3
#define IDENTIFIER 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 144 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"


#line 1213 "../../../code/globalcpp/parser/yyLexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 219 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 218 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 146 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( C_COMMENT ); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 147 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( INITIAL ); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 148 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ ; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 149 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ ; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 150 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ Compiler.CompileError( parsedata.pos - yyleng, "'*/' found outside of comment" ); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 153 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ ; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 154 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ if( prev_yylex != TOKEN_EOL ) YYLEX( TOKEN_EOL ); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 156 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( INITIAL ); YYLEX( TOKEN_EOL ); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 157 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_SIZE ); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 158 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_PERIOD ); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 159 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLLOCSET; TextEscapeValue( yytext + 1, strlen( yytext ) - 2 ); YYLEX( TOKEN_STRING ); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 160 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLLOCSET; TextValue( yytext, strlen( yytext ) ); YYLEX( TOKEN_IDENTIFIER ); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 161 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{
									for ( int i = yyleng - 1; i >= 0; --i )
										unput( yytext[ i ] );

									parsedata.pos -= yyleng;

									BEGIN( INITIAL );
								}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 170 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ if( prev_yylex != TOKEN_EOL ) YYLEX( TOKEN_EOL ); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 171 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ ; }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 173 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLLOCSET; TextEscapeValue( yytext + 1, strlen( yytext ) - 2 ); YYLEX( TOKEN_STRING ); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 176 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_TERNARY ); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 177 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_IF ); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 178 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_ELSE ); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 179 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_WHILE ); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 180 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_FOR ); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 181 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_DO ); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 183 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); yylval.s.val = node1_( method_game ); YYLEX( TOKEN_LISTENER ); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 184 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); yylval.s.val = node1_( method_group ); YYLEX( TOKEN_LISTENER ); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 185 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); yylval.s.val = node1_( method_level ); YYLEX( TOKEN_LISTENER ); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 186 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); yylval.s.val = node1_( method_local ); YYLEX( TOKEN_LISTENER ); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 187 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); yylval.s.val = node1_( method_parm ); YYLEX( TOKEN_LISTENER ); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 188 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); yylval.s.val = node1_( method_owner ); YYLEX( TOKEN_LISTENER ); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 189 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); yylval.s.val = node1_( method_self ); YYLEX( TOKEN_LISTENER ); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 191 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ parsedata.braces_count++; YYLEX( TOKEN_LBRACKET ); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 192 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ parsedata.braces_count--; YYLEX( TOKEN_RBRACKET ); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 193 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLLOCSET; YYLEX( TOKEN_LPAREN ); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 194 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); YYLLOCSET; YYLEX( TOKEN_RPAREN ); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 195 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_LSQUARE ); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 196 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); YYLEX( TOKEN_RSQUARE ); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 198 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_ASSIGNMENT ); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 199 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_COLON ); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 200 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_DOUBLE_COLON ); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 201 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_SEMICOLON ); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 203 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_EQUALITY ); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 204 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_LOGICAL_OR ); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 205 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_LOGICAL_AND ); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 207 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_BITWISE_OR ); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 208 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_BITWISE_EXCL_OR ); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 209 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_BITWISE_AND ); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 210 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_INEQUALITY ); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 211 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_LESS_THAN ); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 212 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_GREATER_THAN ); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 213 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_LESS_THAN_OR_EQUAL ); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 214 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_GREATER_THAN_OR_EQUAL ); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 215 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_NEG ); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 217 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_PLUS ); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 218 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_PLUS_EQUALS ); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 219 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_INCREMENT ); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 220 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_MINUS ); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 221 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_MINUS_EQUALS ); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 222 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_MINUS_EQUALS ); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 223 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_DECREMENT ); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 224 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_MULTIPLY ); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 225 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_MULTIPLY_EQUALS ); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 226 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_DIVIDE ); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 227 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_DIVIDE_EQUALS ); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 228 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_MODULUS ); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 229 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_MODULUS_EQUALS ); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 230 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_SHIFT_LEFT ); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 231 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_SHIFT_LEFT_EQUALS ); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 232 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_SHIFT_RIGHT ); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 233 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_SHIFT_RIGHT_EQUALS ); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 234 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_AND_EQUALS ); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 235 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_EXCL_OR_EQUALS ); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 236 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_OR_EQUALS ); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 237 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ BEGIN( VARIABLES ); YYLEX( TOKEN_DOLLAR ); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 238 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_NOT ); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 239 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_COMPLEMENT ); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 241 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_PERIOD ); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 243 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_COMMA ); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 244 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_NUMBER ); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 246 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_NULL ); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 247 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_NIL ); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 249 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLLOCSET; sscanf( yytext, "%d", &yylval.s.val.intValue ); YYLEX( TOKEN_INTEGER ); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 250 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLLOCSET; sscanf( yytext, "%f", &yylval.s.val.floatValue ); YYLEX( TOKEN_FLOAT ); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 252 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_TRY ); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 253 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_CATCH ); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 254 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_SWITCH ); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 256 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_CASE ); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 257 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_BREAK ); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 258 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_CONTINUE ); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 260 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_MAKEARRAY ); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 261 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ YYLEX( TOKEN_ENDARRAY ); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 263 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{
									if( UseField() )
									{
										parsedata.pos -= yyleng;
										REJECT;
									}
									else
									{
										YYLLOCSET;
										TextEscapeValue( yytext, yyleng );
										YYLEX( TOKEN_IDENTIFIER );
									}
								}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 277 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
{ yylexerror( "bad token:\n" ); }
	YY_BREAK


#undef fprintf


case 92:
YY_RULE_SETUP
#line 285 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1773 "../../../code/globalcpp/parser/yyLexer.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(C_COMMENT):
			case YY_STATE_EOF(C_LINE_COMMENT):
			case YY_STATE_EOF(VARIABLES):
			case YY_STATE_EOF(IDENTIFIER):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 219 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 219 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 218);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 285 "..\\..\\..\\code\\globalcpp\\parser\\yyLexer.l"


